version: "3"

services:
  mongo:
    image: mongo
    environment:
      # IMPORTANT : for learning purposes I'm setting the password 
      # directly but you must not do this in production, use secrets instead
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    restart: unless-stopped
    volumes:
      - mongo-data:/data/db

  mongo-express:
    image: mongo-express
    ports:
    - "8081:8081"
    environment:
      # IMPORTANT : for learning purposes I'm setting the password  
      # directly but you must not do this in production, use secrets instead
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
    restart: unless-stopped
    depends_on:
      - mongo
    
  node-api:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    ports:
    - "8080:8080"
    volumes:
      - /app/node_modules
      - ./backend:/app
    restart: unless-stopped
    depends_on:
      - mongo
      - mongo-express

  react:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
    - "3000:3000"
    volumes:
      - /app/node_modules
      - ./frontend:/app
    restart: unless-stopped
    depends_on:
      - node-api

volumes:
  mongo-data: